import { Inter } from "next/font/google";
import "./globals.css";
//import "./main.module.scss";
const inter = Inter({ subsets: ["latin"] });
import { Header } from "./components/ui/Header";
import { CartProvider } from "./components/context/CartContext.jsx";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <CartProvider>  
        <Header/>
        {children}
      </CartProvider>  
        </body>
    </html>
  );
}
