import { Inter } from "next/font/google";
import "./globals.css";
//import "./main.module.scss";
const inter = Inter({ subsets: ["latin"] });
import Footer from "./components/ui/Footer";
import { Header } from "./components/ui/Header";
import { CartProvider } from "./components/context/CartContext.jsx";
import { AuthProvider } from "./components/context/AuthContext";

export const metadata = {
  title: "Iron Tools Ferreteria🔨",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <AuthProvider>  
          <CartProvider>  
            <Header/>
            {children}
            <Footer/>
          </CartProvider>
      </AuthProvider>  
        </body>
    </html>
  );
}
