import { Inter } from "next/font/google";
import "./globals.css";
//import "./main.module.scss";
const inter = Inter({ subsets: ["latin"] });
import { Header } from "./components/ui/Header";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Header/>
        {children}
        </body>
    </html>
  );
}
